name: Theme Check

on:
  pull_request:
    paths:
      - "theme/**"

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Shopify Theme Check
        uses: shopify/theme-check-action@v3
        with:
          root: theme
